apiVersion: v2
name: dapr-demo
type: application
version: "0.1.0"
appVersion: "0.1.0.01d9fd6_1664451696"
home: https://github.com/joshwrightcodes/ed-demo-dapr
icon: https://github.com/dapr/dapr/raw/master/img/dapr_logo.svg
description: Demo project for using Dapr
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Josh Wright
    email: josh@wright.codes
dependencies:
  - name: opentelemetry-collector
    version: 0.31.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: kafka
    version: 18.4.3
    repository: https://charts.bitnami.com/bitnami
  - name: mailhog
    version: 5.2.0
    repository: https://codecentric.github.io/helm-charts
  - name: courses-api
    version: 0.1.0
    repository: "file://../courses-api/"
  - name: usergroups-api
    version: 0.1.0
    repository: "file://../usergroups-api/"
  - name: users-api
    version: 0.1.0
    repository: "file://../users-api/"