apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  name: {{ include "dapr-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-demo.labels" . | nindent 4 }}
spec:
  mode: sidecar
  config: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      zipkin:
      prometheus:
        config:
          scrape_configs:
            - job_name: "dapr-otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:9090"]
    processors:
      memory_limiter:
        check_interval: 5s
        limit_mib: 1500
        spike_limit_mib: 512
        #        queued_retry:
        #          num_workers: 4
        #          queue_size: 100
        #          retry_on_failure: true
      batch:
        send_batch_size: 1000
        timeout: 30s
    exporters:
      otlp:
        endpoint: dapr-demo-opentelemetry-collector:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [ otlp,zipkin ]
          processors: [ memory_limiter, batch ]
          exporters: [ otlp ]
        metrics:
          receivers: [ otlp,prometheus ]
          processors: [ memory_limiter, batch ]
          exporters: [ otlp ]
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ otlp ]