apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ include "courses-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "courses-api.labels" . | nindent 4 }}
spec:
  {{ if .Values.dapr -}}
  {{ with .Values.dapr -}}
  {{ if .tracing -}}
  tracing:
    samplingRate: {{ default 1 .tracing.samplingRate | int | quote }}
    {{ if .tracing.zipkin -}}
    zipkin:
      endpointAddress: {{ .tracing.zipkin.endpoint | quote }}
    {{- end -}}
  {{- end -}}
  {{- end -}}
  {{- end -}}
