apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "users-api.fullname" . }}-dapr-secret-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ include "users-api.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io